server:
  port: 8081
spring:
  application:
    name: RBloomDemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/easybbs?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.248.135
      port: 6379
      password: 123456